name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup Makefile
      run: cp artifacts/Makefile.noimake .Makefile
    - name: patch
      run: patch -d src -p0 < src/xpacman1.patch
    - name: make
      run: make
